config/routes.rb
Mysdb::Application.routes.draw do
  resources :scouts

end

app/models/medical_form.rb
class MedicalForm < ActiveRecord::Base
  attr_accessible :scout_id, :status
end

app/models/scout.rb
class Scout < ActiveRecord::Base
  attr_accessible :active, :birthdate, :cell_phone, :city, :email, :home_phone, :joined_scouts, :last_medical, :medical_comment, :medical_completed, :name, :photo_release, :roster, :scoutid, :street_address, :type_ids, :work_phone, :zip, :role
  has_many :types
end

app/models/type.rb
class Type < ActiveRecord::Base
  attr_accessible :role, :scout_id
  belongs_to :scouts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/scouts_controller.rb
class ScoutsController < ApplicationController
  # GET /scouts
  # GET /scouts.json
  def index
    @scouts = Scout.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @scouts }
    end
  end

  # GET /scouts/1
  # GET /scouts/1.json
  def show
    @scout = Scout.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @scout }
    end
  end

  # GET /scouts/new
  # GET /scouts/new.json
  def new
    @scout = Scout.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @scout }
    end
  end

  # GET /scouts/1/edit
  def edit
    @scout = Scout.find(params[:id])
  end

  # POST /scouts
  # POST /scouts.json
  def create
    @scout = Scout.new(params[:scout])

    respond_to do |format|
      if @scout.save
        format.html { redirect_to @scout, notice: 'Scout was successfully created.' }
        format.json { render json: @scout, status: :created, location: @scout }
      else
        format.html { render action: "new" }
        format.json { render json: @scout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /scouts/1
  # PUT /scouts/1.json
  def update
    @scout = Scout.find(params[:id])

    respond_to do |format|
      if @scout.update_attributes(params[:scout])
        format.html { redirect_to @scout, notice: 'Scout was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @scout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scouts/1
  # DELETE /scouts/1.json
  def destroy
    @scout = Scout.find(params[:id])
    @scout.destroy

    respond_to do |format|
      format.html { redirect_to scouts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scouts_helper.rb
module ScoutsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>mySDB</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">mySDB</a>
      <div class="nav-collapse">
        <ul class="nav">
        	<li><%= link_to "Browse Scouts", scouts_path %></li>
        	<li><%= link_to "Add Information" %></li>
        	<li><%= link_to "Sign in" %></li>
        	<li><%= link_to "Sign up" %></li>
        </ul>
      </div> 
    </div>
  </div>
</div>
<div class="container">
	<% flash.each do |name, msg| %>
	<div class="alert alert-<%= name == :notice ? "success" : "error" %>">
		<%= msg %>
	</div>
	<% end %>
	<div class="row">
		<div class="span12"><%= yield %></div>
	</div>
</div>
</body>
</html>

app/views/scouts/_form.html.erb
<%= simple_form_for @scout, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.association :types, :label_method => :role, :value_method => :id %>
  <%= f.input :active %>
  <%= f.input :roster %>
  <%= f.input :joined_scouts %>
  <%= f.input :birthdate %>
  <%= f.input :street_address %>
  <%= f.input :city %>
  <%= f.input :zip %>
  <%= f.input :home_phone %>
  <%= f.input :cell_phone %>
  <%= f.input :work_phone %>
  <%= f.input :email %>
  <%= f.input :scoutid %>
  <%= f.input :last_medical %>
  <%= f.input :medical_completed %>
  <%= f.input :medical_comment %>
  <%= f.input :photo_release %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                scouts_path, :class => 'btn' %>
  </div>
<% end %>

app/views/scouts/edit.html.erb
<%- model_class = Scout -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/scouts/index.html.erb
<%- model_class = Scout -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:type_id) %></th>
      <th><%= model_class.human_attribute_name(:active) %></th>
      <th><%= model_class.human_attribute_name(:roster) %></th>
      <th><%= model_class.human_attribute_name(:joined_scouts) %></th>
      <th><%= model_class.human_attribute_name(:birthdate) %></th>
      <th><%= model_class.human_attribute_name(:street_address) %></th>
      <th><%= model_class.human_attribute_name(:city) %></th>
      <th><%= model_class.human_attribute_name(:zip) %></th>
      <th><%= model_class.human_attribute_name(:home_phone) %></th>
      <th><%= model_class.human_attribute_name(:cell_phone) %></th>
      <th><%= model_class.human_attribute_name(:work_phone) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:scoutid) %></th>
      <th><%= model_class.human_attribute_name(:last_medical) %></th>
      <th><%= model_class.human_attribute_name(:medical_completed) %></th>
      <th><%= model_class.human_attribute_name(:medical_comment) %></th>
      <th><%= model_class.human_attribute_name(:photo_release) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @scouts.each do |scout| %>
      <tr>
        <td><%= link_to scout.id, scout_path(scout) %></td>
        <td><%= scout.name %></td>
        <td><%= scout.type_id %></td>
        <td><%= scout.active %></td>
        <td><%= scout.roster %></td>
        <td><%= scout.joined_scouts %></td>
        <td><%= scout.birthdate %></td>
        <td><%= scout.street_address %></td>
        <td><%= scout.city %></td>
        <td><%= scout.zip %></td>
        <td><%= scout.home_phone %></td>
        <td><%= scout.cell_phone %></td>
        <td><%= scout.work_phone %></td>
        <td><%= scout.email %></td>
        <td><%= scout.scoutid %></td>
        <td><%= scout.last_medical %></td>
        <td><%= scout.medical_completed %></td>
        <td><%= scout.medical_comment %></td>
        <td><%= scout.photo_release %></td>
        <td><%=l scout.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_scout_path(scout), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      scout_path(scout),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_scout_path,
            :class => 'btn btn-primary' %>

app/views/scouts/new.html.erb
<%- model_class = Scout -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/scouts/show.html.erb
<%- model_class = Scout -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @scout.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:type_id) %>:</strong></dt>
  <dd><%= @scout.type_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:active) %>:</strong></dt>
  <dd><%= @scout.active %></dd>
  <dt><strong><%= model_class.human_attribute_name(:roster) %>:</strong></dt>
  <dd><%= @scout.roster %></dd>
  <dt><strong><%= model_class.human_attribute_name(:joined_scouts) %>:</strong></dt>
  <dd><%= @scout.joined_scouts %></dd>
  <dt><strong><%= model_class.human_attribute_name(:birthdate) %>:</strong></dt>
  <dd><%= @scout.birthdate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:street_address) %>:</strong></dt>
  <dd><%= @scout.street_address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:city) %>:</strong></dt>
  <dd><%= @scout.city %></dd>
  <dt><strong><%= model_class.human_attribute_name(:zip) %>:</strong></dt>
  <dd><%= @scout.zip %></dd>
  <dt><strong><%= model_class.human_attribute_name(:home_phone) %>:</strong></dt>
  <dd><%= @scout.home_phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cell_phone) %>:</strong></dt>
  <dd><%= @scout.cell_phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:work_phone) %>:</strong></dt>
  <dd><%= @scout.work_phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @scout.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:scoutid) %>:</strong></dt>
  <dd><%= @scout.scoutid %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_medical) %>:</strong></dt>
  <dd><%= @scout.last_medical %></dd>
  <dt><strong><%= model_class.human_attribute_name(:medical_completed) %>:</strong></dt>
  <dd><%= @scout.medical_completed %></dd>
  <dt><strong><%= model_class.human_attribute_name(:medical_comment) %>:</strong></dt>
  <dd><%= @scout.medical_comment %></dd>
  <dt><strong><%= model_class.human_attribute_name(:photo_release) %>:</strong></dt>
  <dd><%= @scout.photo_release %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              scouts_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_scout_path(@scout), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              scout_path(@scout),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>